### ISSUE TITLE
The source code of jstorrent has disappeared

### ISSUE THREAD

**Issue by mossroy** [kzahel/jstorrent-legacy-app#1]
And all the issues too.
Based on the README (the only file left), it is "due to licensing issues".

Could you give more info (if you're allowed to)?

**Comment by kzahel** [comment]
My former employer asked me to take it down.

I might do a from-scratch rewrite, but that would take some (precious) time...

**Comment by kzahel** [comment]
(and now it's gone from the CWS too)
