### ISSUE TITLE
Downloading STOPS no matter % complete

### ISSUE THREAD

**Issue by sebanderson** [kzahel/jstorrent-legacy-app#103]
I downloaded JSTorrent from the Google Store (paid $3). When I add a torrent, I get decent speeds for a minute or two. However, no matter what size the file is (big or small), the number of peers it has, etc. - the download will stop. 

I'm downloading one album that stopped at 16.7%, and another that stopped at 47.1%. It will sometimes go back up to 1-3 bits per second, but then die again. The status says "Started", but the file doesn't download.

I've tried minimizing the client. I've tried pressing "Stop" and "Start" (works for a few seconds, but then it dies again). I've tried restarting the application. Nothing works. Most peers have a 100% completion, so that's not the problem.

I'm not sure what to do, but since I paid for this app (on Google), I would appreciate if you would help me get it working right.

**Comment by kzahel** [comment]
Are you skipping certain files? The percent complete indicator may not be accurate. Check the files tab.

**Comment by deanwjackson** [comment]
I have this same problem, and it isn't the completion indicator--my files haven't finished. After a few minutes of downloading at full speed, JSTorrent ETA times change to "Infinite" (or thousands of days) and stay that way until I restart.

Did anyone ever find a fix for this?

**Comment by kzahel** [comment]
How many GB are you downloading? If it's more than around 5GB this is
expected behavior, as there is likely some kind of memory leak that I
haven't identified yet. For torrents of such large size, it's better to use
more mature torrent software e.g. transmission/utorrent

**Comment by deanwjackson** [comment]
Kyle--it's a 2.35 GB file. Unfortunately, I'm using a chromebook, so
(unless I'm mistaken!) a more mature client isn't an option!

Thanks for your reply. :)

**Comment by kzahel** [comment]
Hi, the latest update fixes problems with large files hanging/stopping. I tested now for several days downloading many many gigabytes. No problems. Give it a shot!
