### ISSUE TITLE
I'm confused - where is the app?????

### ISSUE THREAD

**Issue by emmasheffield** [kzahel/jstorrent-legacy-app#11]
I paid for the JSTorrennt app yesterday, and paid for it using my Google Wallet account and even still not it says i haven't paid for it. I have even tried to use my partners account to pay for it again, and again, it still hasn't worked. Am I doing something wrong?? when i go onto the app of the store, it says 'free' so i click on it, and then it says 'installing' and then goes back onto the 'free' section again. The app isn't appearing anywhere in my downloads. Where do i find it, if it has downloaded??????? I'm so confused.

**Comment by kzahel** [comment]
You should be able to get to it via the launcher app. I.e. on a chromebook
click on the "start menu" and you should be able to scroll through your
apps and find it there. Or even search inside the launcher app.

**Comment by emmasheffield** [comment]
Nope. Definitely not there. Tried to purchase twice now, both times been charged to my account, and still the app is no where to be seen. Not showing on my apps, or on the downloads through Google Drive. It's as if it doesn't exist.

**Comment by kzahel** [comment]
Google is really messing up their chrome web store. You're like the third
person who's brought this to my attention.
If you email me at graehlarts@gmail.com with your transaction numbers I can
refund the duplicate purchase.

Use the trial version for now, if you need to download a torrent right
away. It can be gotten if you install "JSTorrent Helper extension", it pops
up a notification with a link.
