### ISSUE TITLE
No peers received

### ISSUE THREAD

**Issue by mwilk84** [kzahel/jstorrent-legacy-app#111]
Every time I try to download, I get the error that states "No peers received from any trackers. Unable to download. Try a more popular torrent or a different torrent site." I get this with any torrent, from any site. I'm running version 2.3.10.

**Comment by mwilk84** [comment]
Do you have any suggestions? Still having this problem.

**Comment by kzahel** [comment]
Hi sorry I did not get back to you sooner. If you aren't able to download anything, there could be an issue with your ISP blocking torrent traffic, though I have never personally experienced this.

Are you able to try on a windows or mac using another program such as transmission? Do those work?

**Comment by kzahel** [comment]
Try with the new version, it has an updated list of public trackers
