### ISSUE TITLE
Error with every torrent #44

### ISSUE THREAD

**Issue by Madfish39** [kzahel/jstorrent-legacy-app#114]
Hi, am new to using js torrents, I am getting a error with every torrent I try to download, i am also used to using magnet links but they say not supported on chrome os. I also dont see how you can right click on the torrent to then choose js to open it with, any hep appriciated, like I say I am used to using windows and a bit torrent client not js which I have now paid for, or chrome os, thanks

**Comment by kzahel** [comment]
Hi, to get the right click menu, install the extension: https://chrome.google.com/webstore/detail/jstorrent-helper-extensio/bnceafpojmnimbnhamaeedgomdcgnbjk

It should work fine on windows.

Try to stick to magnet links, they usually work better

**Comment by Madfish39** [comment]
I have the correct extension, but not working and am on a chromebook acer c270........every torrent I download giving me an error in JS

**Comment by FeniXrisN** [comment]
I keep getting an error message with every torrent as well. Downloading on Chromebook into google drive. It seemed to work for up to a gig on one torrent, but now I get error message and I have tons of space on my google drive account.

**Comment by kzahel** [comment]
Don't save to google drive directly. It will try to "sync" as it downloads, causing massive slowdown and errors as it re-uploads every time the file changes as you are downloading.
Save to a local folder (such as Downloads, or an SD Card, or USB Drive) first, and transfer later to google drive if you need to

**Comment by FeniXrisN** [comment]
Thank you!
