### ISSUE TITLE
Update Public Trackers List

### ISSUE THREAD

**Issue by pogue** [kzahel/jstorrent-legacy-app#116]
In light of the fact that Demonii has shut down, I think it would be great if JsTorrent could update it's internal list of public trackers it uses when it can't find sources.  Reddit has a big list of all the open public trackers on /r/OpenTrackerProject.
https://www.reddit.com/r/opentrackerproject/comments/3qyequ/tracker_list_report_october_31_2015/

A lot of times, when it polls the trackers, majority of them end up timing out with no response.  I believe I noticed that the common.js has 3 trackers listed, but I'm using the version uploaded to the Chrome Store, so I assume that one is different.

Thanks!

**Comment by kzahel** [comment]
Hey, thanks so much for the tip. I see some of the ones I was using are indeed on the "dead" list. I'll have to update them this week.

**Comment by kzahel** [comment]
I finally put in some new trackers in the latest release. Now just need to use DHT too...
