### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by o-Epictetus-o** [kzahel/jstorrent-legacy-app#120]
When will JSTorrent be updated in the Chrome Store? It says the last time it was update was January 19, 2015!

**Comment by kzahel** [comment]
What feature do you want updated? Or is there a bug you want to report? There haven't been any notable changes since then. I do plan on doing some work in Q1 2016, so let me know what features you think are missing.

**Comment by o-Epictetus-o** [comment]
The ability to have unlimited seeds! At current standing it limits me to a certain amount or it refuses to download.

**Comment by kzahel** [comment]
I released a new version, let me know how it goes!

**Comment by o-Epictetus-o** [comment]
Still only 200 connections per torrent. Why not allow unlimited?

**Comment by o-Epictetus-o** [comment]
Also I tried downloading a file with utorrent and jstorrent at the same time on a 180Mbps connection. Utorrent was downloading at 1.6MBps while JSTorrent wouldnt pass 250.
