### ISSUE TITLE
something that helped me

### ISSUE THREAD

**Issue by timisalf** [kzahel/jstorrent-legacy-app#121]
when i first started using this for downloading i was getting stuck with low speeds and sometimes it wouldn't work at all, just sit at 3b/s. i was searching for a way to decrease lag for my lower end chrome book and this link https://gigaom.com/2013/04/05/running-out-of-memory-on-a-chromebook-heres-a-30-second-solution/ helped with that problem. what i also noticed though is that my speeds increased to 800kb/s to 1mb/s after i did this and performed a reboot. not sure if this was the solution but i can say that I'm operating at 100% now. Just a thought.

i apologize if this is the wrong area to post this. (i will remove it if you want me to or you can remove it)

**Comment by kzahel** [comment]
Thanks for posting the tip. I identified a lot of problems that were causing the downloads to hang. Try the new version.
