### ISSUE TITLE
_locales subtree is missing

### ISSUE THREAD

**Issue by Bahjesaispas** [kzahel/jstorrent-legacy-app#125]
Impossible to intall the extension on my chromebook.
Error message :
Default locale was specified, but _locales subtree is missing.
1
![screenshot 2016-04-13 at 13 34 55](https://cloud.githubusercontent.com/assets/11292209/14491997/8b7e5d06-017c-11e6-9c70-4fd7e84fdaba.png)

**Comment by kzahel** [comment]
thanks! adding it!

**Comment by beaufortfrancois** [comment]
So much better now ;)
Thanks @kzahel !
