### ISSUE TITLE
Changelog keeps popping up since last update

### ISSUE THREAD

**Issue by maevelander** [kzahel/jstorrent-legacy-app#129]
Every single time I open browser since 13th April update the popup telling me it's updated pops up. Super annoying!  I've clicked it, checked settings, there seems no obvious way to stop it doing that. Bug I reckon...

**Comment by kzahel** [comment]
Thanks for the report. I'm trying to reproduce the problem. Are you on ChromeOS? Dev channel?

**Comment by maevelander** [comment]
Cool, thanks. I do run ChromeOS at home and yes dev channel. But interestingly the problem happens on my Work PC which is Windows 7 and NOT on the ChromeOS at home (although of course Google Apps syncs between the two). Let me know anything I can do to help.

**Comment by kzahel** [comment]
![screenshot 2016-04-21 at 9 13 47 pm](https://cloud.githubusercontent.com/assets/158352/14731511/fb251d22-0805-11e6-9c68-7a6cfbc484f0.png)

**Comment by kzahel** [comment]
I think I may see the problem

**Comment by kzahel** [comment]
https://github.com/kzahel/jstorrent/commit/15cc79ae7a66dacdf782b093e1ebdcafe46ff255
will push out an update later today

**Comment by maevelander** [comment]
Nice one, thanks!
