### ISSUE TITLE
Extension fails to detect certain URLs

### ISSUE THREAD

**Issue by ghost** [kzahel/jstorrent-legacy-app#14]
Extension fails to detect URLs pointing to `.torrent` files and having `?`, `#` or `&` characters. (example links: http://jsfiddle.net/arpitnext/sfejt/4/embedded/result/).

The `targetUrlPatterns` in [this file](https://github.com/kzahel/jstorrent/blob/fresh/extension/background.js) requires more options.

**Comment by kzahel** [comment]
Awesome, thank you. Fixed 066a81b061ec050985c6556dac4eefc9022445d4
Except actually one of those urls is not valid (the http://domain.com/path/file.torrent&hello=23) so there is no pattern for that.
