### ISSUE TITLE
(Feature-Request) Open Torrent File

### ISSUE THREAD

**Issue by meyersbs** [kzahel/jstorrent-legacy-app#140]
I would like to be able to open an already downloaded torrent file. Some sites do not provide magnet links and many of their torrent URLs are interpreted as invalid by JSTorrent.

**Comment by kzahel** [comment]
Click on "Add" without entering a URL, it should pop up a dialog to select a .torrent file

**Comment by kzahel** [comment]
Also you should be able to drag in a .torrent file from the file browser, too.

**Comment by meyersbs** [comment]
Well, now I feel stupid!

**Comment by kzahel** [comment]
It's not obvious at all, honestly... I'm wondering how to make it more discoverable...

**Comment by meyersbs** [comment]
Honestly, I would have a separate 'Open' button.
