### ISSUE TITLE
jstorrent

### ISSUE THREAD

**Issue by joemarlapinid** [kzahel/jstorrent-legacy-app#142]
i can't start downloading any torrent files because it always says that,

Web Server Chrome library was not loaded and is now required. GET IT
The files should go in the JSTorrent folder under js/web-server-chrome
(NOT js/web-server-chrome-master)

I already downloaded the WSC Library. Can you help me fix this problem with my JSTorrent? I cannot start  downloading because of this. Please. Thank you :-)

**Comment by kzahel** [comment]
You need to download web-server-chrome from github, unzip it and put it in the js folder. Make sure it's called web-server-chrome, not web-server-chrome-master
