### ISSUE TITLE
Version 2.4.3?

### ISSUE THREAD

**Issue by FoxInFlame** [kzahel/jstorrent-legacy-app#147]
On the Chrome Web Store and on the official website, it says that JSTorrent is at Version 2.4.3.

I downloaded the source code as a ZIP file and installed it, and checked the version in chrome://extensions, and in the Help page, and I realized that the version was 2.4.12. 

Please update the source code!

**Comment by Kriskras99** [comment]
You realize that 12 is higher than 3?

The source code is actually more up to date than JSTorrent in the Chrome Web Store, this is probably to test the reliability of the code before pushing a new version to the Chrome Web Store.

**Comment by FoxInFlame** [comment]
Is it 12? I thought it means 1, and then 2, like as in 1.2

**Comment by Kriskras99** [comment]
Then it would say 2.4.1.2 ;)

**Comment by FoxInFlame** [comment]
Ah. Version numbers always confuses me. :)

Love the app, but would like a redesign!
