### ISSUE TITLE
Magnet URL cause JS error

### ISSUE THREAD

**Issue by SmokyBob** [kzahel/jstorrent-legacy-app#16]
After updating to the latest version, previously working magnet URLs case the error in the screenshot
![screenshot 2014-01-18 at 11 52 39](https://f.cloud.github.com/assets/1431346/1946892/98de0972-802f-11e3-8907-12a2f1a8b7c7.png)

(Edited screenshot for a smaller image)

First and Fourth links were added using a magnet URL like the following:
magnet:?xt=urn:btih:0000000000000000000000000000000000000000&dn=torrentname&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.publicbt.com:80&tr=udp://tracker.istole.it:80&tr=http://tracker.istole.it&tr=http://fr33dom.h33t.com:3310/announce

Adding that caused the error displayed in the notification.
Tested with a same format magnet url used to download a file with the previous version and got the same error.

The other files are added by adding the .torrent file download URL and they work flawlessly.

If any other information are need let me know.

**Comment by kzahel** [comment]
Thanks for the bug report. I am able to reproduce this. I'm looking into it now, will let you know what happens...

**Comment by kzahel** [comment]
Ah, I found the race condition. Nothing major :-) bb4125e3b587e336cacf60bf3c78b81abc3bc4c5 
Will roll version 2.1.1 soon with the bugfix.
I owe you a beer ;-)

**Comment by SmokyBob** [comment]
Woah what a fast Fix.

Don't Joke Man, we all how you a lot.
The app keep getting better and better and it's essential for Chrome OS device (well... even on my other OSes other torrent clients are gone now)
