### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by Modeliukas** [kzahel/jstorrent-legacy-app#168]
My Order Number for  JSTorrent : 10370910874874185126.e0d7db0955f6465aaea67f29c1e34f25 . My question is was this price per month or one time purchase fee as i dont want to get charged every month. Because i want a refund . Thanks

**Comment by kzahel** [comment]
The order is canceled

**Comment by Modeliukas** [comment]
okay so i will not get charged next month

**Comment by kzahel** [comment]
nope its one-time purchase, but you already canceled it.
