### ISSUE TITLE
Port JSTorrent to Firefox

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [kzahel/jstorrent-legacy-app#180]
Do you remember a similar feature request in #55? Since Firefox Quantum released, it’s possible to port your extension to Firefox, but you don’t need so hard works to do.
Then MDN will teach you how to port your Chrome extension.
https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions

**Comment by ExE-Boss** [comment]
This won’t be very doable because this is&nbsp;actually a&nbsp;Chrome app with a&nbsp;helper extension.

**Comment by kzahel** [comment]
The main problem is no raw socket support and probably not raw filesystem access
