### ISSUE TITLE
No support for japanese or korean characters.

### ISSUE THREAD

**Issue by asterne-labs** [kzahel/jstorrent-legacy-app#23]
Presumably, there's no support for other characters either, but those are the only two I've tested. You end up with a jumbling of characters for the torrent name and a cluster of error messages popping up in your notifications.

**Comment by kzahel** [comment]
I'm probably not doing utf-8 decoding correctly. I would fix it faster if you were able to send me infohashe/torrent files that cause it to break - graehlarts@gmail.com

**Comment by asterne-labs** [comment]
Here's an example of a torrent that breaks it.
http://www.nyaa.se/?page=view&tid=529118

Also, I've noticed, if you use a magnet link to load the torrent, the
name will load correctly until it actually attempts to start
downloading the file, it seems like, but if you use a .torrent file,
it immediately spits out the errors.

**Comment by kzahel** [comment]
Thanks for the link. I tested and it seems to work with that torrent now. I haven't tried with any other torrents. I'll try with some russian etc stuff later and make sure it hasn't broken any other torrents...
https://github.com/kzahel/jstorrent/commit/d14748aa1a5a579a6c8598291d5c128399d600f3

**Comment by asterne-labs** [comment]
Will updating cause progress on torrents currently downloading to be lost, or will it be okay if I update while in progress?

**Comment by kzahel** [comment]
you're running from source, right? if you do a "git pull" it will keep your
data, however if you put it in a new folder / unzip somewhere new, it will
reset all your data...

**Comment by asterne-labs** [comment]
As I'm working on a chromebook without being in dev mode, I don't
believe I can use the "git" command, so I'll just wait until finishing
my current torrents to update, I suppose.

**Comment by kzahel** [comment]
Don't update -- it seems my "fix" has made it worse... I'll try again :-)

**Comment by kzahel** [comment]
Ok it should be workable now 67ec547e28d5c25a7ff952028ee0d98a13a0fdd4

**Comment by asterne-labs** [comment]
Alright, thanks. A good number of torrents I download have non-english characters in them, so this was a bit of a big issue for me.

**Comment by kzahel** [comment]
Sorry it's taking so long to release this fix. I am moving and that's taking up a bunch of time. Should have another release soon

**Comment by kzahel** [comment]
It is released now. Let me know if you have any trouble!
