### ISSUE TITLE
QuotaExceededError messaging

### ISSUE THREAD

**Issue by kzahel** [kzahel/jstorrent-legacy-app#28]
have it say "out of disk space" instead

**Comment by LibanTheDev** [comment]
What would  I have to do to resolve this QuotaExceededError?

**Comment by kzahel** [comment]
That means you're low on hard drive space. Either download to an external
USB drive or clear up some space in your Downloads folder

**Comment by LibanTheDev** [comment]
Thanks! I figured it out last night. Btw JSTorrent is a nice app.
