### ISSUE TITLE
JSTorrent won't download torrents.

### ISSUE THREAD

**Issue by plainskotti** [kzahel/jstorrent-legacy-app#30]
Connections keep timing out. Worked Friday night on downloading, but now it just doesn't connect at all.

**Comment by kzahel** [comment]
How many are in the "Swarm" (count # of rows in "Swarm" tab or look at the Swarm column of the torrent, or look at the "Trackers" tab and count the # of seeds)

**Comment by plainskotti** [comment]
Absolutely none on jstorrent. It won't even connect to the "swarm" or any seeders/leechers. 

On the tracker there is over 2000 seeders/leechers/

**Comment by kzahel** [comment]
That indicates jstorrent has a problem connecting to the tracker. Are there any error messages? Is it a private tracker?

**Comment by plainskotti** [comment]
Seemed to resolve itself. If I could explain why, I would.

**Comment by kzahel** [comment]
Hmm. Perhaps the trackers were down temporarily

**Comment by plainskotti** [comment]
So I'm still having an issue. I'm using the pirate bay and adding the magnet links by right clicking on the link and hitting add to JSTorrent. Is it an issue with The Pirate Bay? or do magnet links not work? The torrent shows up, just all the connections time out.

**Comment by kzahel** [comment]
How many peers in the swarm? Perhaps the peers simply aren't online. I've never had a problem with large swarms (>20)

**Comment by plainskotti** [comment]
Over 500. I think I may have found the issue. I can download at home, but work blocks my torrent traffic. Sorry I bothered you. If you have any solution to this it'd be helpful. I seem to be able to connect to all the tracker servers except one.

**Comment by kzahel** [comment]
Hmm interesting.
It would be great if you are able to test if they are able to block
uTorrent as well when you enable protocol encryption. That supposedly can
get around blocking, though it depends on how aggressive they are at
blocking.

**Comment by plainskotti** [comment]
Unsure. It's weird because when I first got your app, I could download fine. I work at a hotel, and before I switched to a chromebook I used a windows 8.1 laptop with utorrent and never had any issues. Either A: they caught on to the torrenting, or B: there is an inside issue somewhere with the server program we use to control traffic flow and your app.

**Comment by kzahel** [comment]
uTorrent might automatically try to use protocol encryption when it detects
it's being blocked, which might explain that.

**Comment by plainskotti** [comment]
Ahhh. So is there something I can do on your app, or is there something I can report to you to see if you can fix it?

**Comment by kzahel** [comment]
I would need to add support for protocol encryption to JSTorrent, which
would be a fair amount of work. But doable.

If you want to help test my hypothesis, you could re-try with your windows
8 machine and uTorrent at the same time / same hotel connection, but it
sounds like you travel around a lot so you can't really make an exact test.

But I'm pretty sure this is what's happening.

Have you considered using a VPN? That would be able to get around traffic
restrictions.

**Comment by plainskotti** [comment]
I have since gotten rid of my windows laptop. It would be nice, but not necessary for the encryption. It's just a matter of me wanting to download at work as opposed to my home network where internet is slower. Thanks though!

**Comment by kzahel** [comment]
Definitely putting protocol encryption on my to-do list! Thanks for the
troubleshoting

**Comment by plainskotti** [comment]
Hey, I brought my gfs laptop to work with me tonight with Win7 and uTorrent. Without protocol encryption it wouldn't download anything, and then with it enabled, it acheived 800kB/s in a swarm of 6000. It was slow to start but did end up getting the torrent downloaded. 

Just figured you would want to know that it was indeed my work throttling the connection and not your app. Other than that I loved it! Cheers and good luck on it.

**Comment by kzahel** [comment]
awesome, thanks for doing that. I will definitely need to add protocol
encryption, as I'm sure there are a ton of people who have the same issue.
