### ISSUE TITLE
Constant errors

### ISSUE THREAD

**Issue by misssarafirefly** [kzahel/jstorrent-legacy-app#32]
I have been trying to use this app for months and no matter what, I get errors. Does jstorrent even work? This happens constantly and its getting tiring. I have attached screenshots. What should I do to make it work, or get my money back??

![screenshot 2014-04-29 at 7 07 05 pm](https://cloud.githubusercontent.com/assets/7444416/2835979/0110337c-cff3-11e3-8e2e-0ea406d9031f.png)

**Comment by kzahel** [comment]
Hey, sorry about the trouble. I have been seeing this error in the logs, though it is very infrequent.
You should be able to fix it for now, by doing the following:
- type "chrome://inspect" into the URL bar
- click on "Apps" on the left
- click "Inspect" next to JSTorrent
- click on "Console" near the top of the window that pops up
- type "app.reinstall()"

I will of course fix this issue in the next release. Thank you for the bug report.
If you ever want a refund, just request it through the play store and I will refund you.

**Comment by kzahel** [comment]
This should be fixed now with the latest release.
