### ISSUE TITLE
Switch to the new chrome.sockets API

### ISSUE THREAD

**Issue by beaufortfrancois** [kzahel/jstorrent-legacy-app#35]
As you can read at https://developer.chrome.com/apps/socket, _Starting with Chrome 33, this API is deprecated in favor of the sockets.udp, sockets.tcp and sockets.tcpServer APIs._

It is pretty easy to do the transition. See https://github.com/GoogleChrome/chrome-app-samples/commit/4af69d063aa549703a73a5bb06db612ed5081a35

**Comment by kzahel** [comment]
Thanks yea I know I need to do this soon :-)

**Comment by kzahel** [comment]
6c6662651512dee850f948ed5c54e75534e7b680
I like the new API, it feels much cleaner than the old one.

**Comment by beaufortfrancois** [comment]
It does!
