### ISSUE TITLE
Error Persisting Piece : QuotaExceededError

### ISSUE THREAD

**Issue by CozaMcCoza** [kzahel/jstorrent-legacy-app#39]
It's happening to all my torrents after I force start them.  After about a minute they all fail.  I am sometimes able to get an increase in percentage but as I have to keep force starting, it's not really viable.

I am using JSTorrent version 2.2.6 and the platform is on a Chromebook (HP11)

Google Chrome   34.0.1847.134 (Official Build 266018) 
Platform    5500.130.0 (Official Build) stable-channel daisy_spring
Blink   537.36 (@171891)
JavaScript  V8 3.24.35.33

**Comment by kzahel** [comment]
This means you're out of disk space. Clear out some files from your download folder.

**Comment by CozaMcCoza** [comment]
Just after I posted this I thought I would check this and I definitely think I am out of disk space (only having 16GB soon makes you remember you have limited space).  I'm trying to open up my file viewer but it's stuck on loading, definitely making me think that I am out of space.  Thanks for the quick response

**Comment by kzahel** [comment]
One tip for when the file browser gets stuck loading. I think there is a
ChromeOS bug in the files app -- if you create a "new window" in the files
app, the other window that was stuck loading will then finish loading. Let
me know if that fixes the stuck loading problem.

**Comment by CozaMcCoza** [comment]
I've already tried that, now I have multiple stuck windows. I also can't
access anything in JSTorrent to delete any of the current downloading files
as I get the error:

In file js/deps/google-analytics-bundle.js at line 23, Uncaught
AlreadyCalledError: Deferred has already fired

**Comment by kzahel** [comment]
Damn. Seems like a bug with the Filesystem API. I would suggest rebooting

**Comment by CozaMcCoza** [comment]
Already tried that too. I'll let you know as soon as I get anywhere and
when I find a fix. Thanks

**Comment by kzahel** [comment]
You may want to type chrome://inspect into your URL bar and click on the
Files app that is hanging, and look in the console for errors; and possibly
report a bug to crbug.com (google's issue tracker)

**Comment by CozaMcCoza** [comment]
I tried that but couldn't find any useful data to send back (unless you
mean lines of what looks like HTML code).  Just to update you,  I cleared
my cache and that allowed me to open up the Files app and view my files.
 Currently moving a load over now to create a bit more space.  Once the
files have moved I'll try JS Torrent again and possibly only do one torrent
download at a time.

Also, I am currently in Peru and I am unable to buy your app, but as soon
as I enter a country where it is possible for me to purchase it, I will do
so.

Thank you for the support and the speed of it too.

**Comment by kzahel** [comment]
Strange. I haven't been able to figure out why the Files app is hanging
sometimes either. It's good to know that resetting cache helps.

Thanks so much for the bug report!

**Comment by CozaMcCoza** [comment]
Just incase anyone else stumbles across this:

I tried to enable swap (by pressing ctrl+alt+t) and typing "swap enable".
This did not fix it and after resetting I switched back to "swap disable"

**Comment by kzahel** [comment]
Latest ChromeOS update seems to have fixed the Files app problem for me.
