### ISSUE TITLE
Error with every torrent

### ISSUE THREAD

**Issue by gonzalezrbrenden** [kzahel/jstorrent-legacy-app#44]
Every single torrent i open i get invalid torrent.

**Comment by kzahel** [comment]
You're downloading a .torrent file and opening with the app?
Can you send one to me at graehlarts@gmail.com and I can debug the problem

**Comment by gonzalezrbrenden** [comment]
Just sent email and yes a .torrent file and its invalid every time.

**Comment by kzahel** [comment]
Interesting, the File association seems to be missing. Try dragging the .torrent file into the app

**Comment by kzahel** [comment]
Do you see the error "This file type is not supported" when you click from the Files app? I'm seeing this too. I think google maybe messed up custom file handlers with their latest update...

**Comment by gonzalezrbrenden** [comment]
Still invalid torrent this is the first problem ive had was working fine a week ago. And it says the file is supported by your app.

**Comment by kzahel** [comment]
Strange, when I drag it in, I don't get any errors. It adds the torrent and starts downloading. Are you using ChromeOS?

**Comment by gonzalezrbrenden** [comment]
Yes i am using ChromeOS Version 35.0.1916.155 on HP Chromebook 11

**Comment by kzahel** [comment]
Okay I'll give it a shot on my HP 11 then. It's working on my pixel

**Comment by gonzalezrbrenden** [comment]
okay thank you.

**Comment by kzahel** [comment]
Cool I'm seeing a problem on the HP 11. It's actually just not even trying to load the torrent at all. Is that what you're seeing? Or an error about an invalid torrent?

**Comment by gonzalezrbrenden** [comment]
Im getting an error about an invalid torrent file when its not.

**Comment by kzahel** [comment]
Are you running from source or through the official install in the web store. Can you attach a screenshot of the error message?

**Comment by gonzalezrbrenden** [comment]
Source i wanted to test before buying and don't
![screenshot 2014-06-13 at 3 01 12 pm](https://cloud.githubusercontent.com/assets/7471952/3274903/9cc70ee8-f335-11e3-820c-971ea34e0f93.png)
 have money to buy at moment.

**Comment by kzahel** [comment]
I really appreciate your reporting this bug. So I just tested again on my
HP11 and fixed the other issue I was having. However I'm on dev channel
(37.0.2041.6 dev) and am not seeing the error. Is there any chance you
could set a breakpoint at
https://github.com/kzahel/jstorrent/blob/fresh/js/torrent.js#L361
(torrent.js, line 361) and give me a screenshot of the stack trace? I'm
kind of stumped...

**Comment by kzahel** [comment]
Actually if you pull or re-download now, I am no longer catching the
exception, so it will print out the actual error, if you can do that

**Comment by gonzalezrbrenden** [comment]
Here's your error. 
![screenshot 2014-06-13 at 3 20 29 pm](https://cloud.githubusercontent.com/assets/7471952/3275157/549dc046-f338-11e3-99c4-37cad28c7e2f.png)

**Comment by kzahel** [comment]
Ah, of course. You're missing a submodule (web-server-chrome). Give me a few minutes to fix this...

**Comment by gonzalezrbrenden** [comment]
Okay glad you can fix it thank you please let me know when its fixed ill defiantly be buying when i have the money.

**Comment by kzahel** [comment]
Okay give it another shot. Thanks again for reporting the error!

**Comment by gonzalezrbrenden** [comment]
Okay it works now thank you and no problem.
