### ISSUE TITLE
Error with every torrent

### ISSUE THREAD

**Issue by jnrvdtak** [kzahel/jstorrent-legacy-app#45]
Hey, 

Since a week or so my JStorrent keeps giving errors, not one torrent has completed a download since. My Chromebook freezes or gets very slow when I start JStorrent and i'm getting this message alot:

Error with torrent: error persisting piece: entrygeterror

What can I do to fix this?

Please help!

**Comment by kzahel** [comment]
The only time I've seen this error is when you're out of free hard disk space. Can you check that you have free space on the disk that you're downloading to? Check your download directory in the options, and then you can see how much free disk space by looking in the ChromeOS "Files" app, navigating to the correct drive, and clicking on the gear icon (preferences)

**Comment by kzahel** [comment]
fixed with better error messaging. It will now say out of disk space.

**Comment by 4G0N** [comment]
I have plenty of disk space and am getting this error.

**Comment by wellrest** [comment]
I am getting the exact same error... trying to download a 400 MB file with 5+ gigs free.  It used to work great, not sure what's going on...

**Comment by wellrest** [comment]
Established a different download directory, got an error offering to kill dl folder, deleted offended folder, works fine.

**Comment by rvenie** [comment]
Getting the same, but my i have lot of free memory available. 
chromeos 50, jstorrent 2.4.8
