### ISSUE TITLE
Web Crypto API

### ISSUE THREAD

**Issue by cwegener** [kzahel/jstorrent-legacy-app#49]
Consider using Chrome's implementation of WebCrypto API for hash generation.
http://crbug.com/379976
https://docs.google.com/a/chromium.org/document/d/184AgXzLAoUjQjrtNdbimceyXVYzrn3tGpf3xQGCN10g/edit

**Comment by kzahel** [comment]
Cool I definitely will look into this. The spec looks very good. I see a simple example on http://www.w3.org/TR/2013/WD-webcrypto-usecases-20130108/

```
      bufferData = createArrayBufferView(src);
      var digest = window.crypto.digest("SHA-256", bufferData);
      digest.finish();
      digest.oncomplete = ...
```

**Comment by cwegener** [comment]
Hopefully it's easy to implement in JStorrent. Should make it much more usable on low CPU devices. On my HP Chromebook 11, I don't get much CPU time left when a torrent is downloading at high speed.

And WebCrypto API will be enabled by default in Chrome 37, so once M37 has a stable release, all JSTorrent users can take advantage of it right away.

**Comment by kzahel** [comment]
I actually have a HP11 in dev channel so I'll be able to do some benchmarking with this next week. I should be able to ship it before 37 goes stable too by using it conditionally when its available

**Comment by kzahel** [comment]
This is very sad...
so apparently the current spec does not even allow progressive hashing, which would mean using it would be very inefficient in terms of memory use. I would be making a copy of all the downloaded chunks just to hash them.
http://lists.w3.org/Archives/Public/public-webcrypto/2013Sep/0023.html

**Comment by kzahel** [comment]
But apparently progressive operations aren't implemented because they're too complex to code in blink, "horrendously complex"
http://lists.w3.org/Archives/Public/public-webcrypto/2013Sep/0026.html

So I guess I'll just try with copying and see how that works in terms of performance

**Comment by kzahel** [comment]
https://github.com/kzahel/jstorrent/commit/f1b4d2acf5721ea121068d26d965a7bd573a4268

It seems to work pretty well on my HP11 in dev channel.

**Comment by kzahel** [comment]
looks like it was moved to M37, so we have to wait another 2 months or so till its shipped..

**Comment by cwegener** [comment]
My HP11 is my daily production machine! Certainly don't want to move that to dev channel.
In the chromium bugs for the WebCrypto API implementation I have read though, that the WebCrypto API will eventually trickle into the other releases via 'experimental Web API' flags ... I just can't seem to figure out if that means it will show up in current stable (M35)

I'll probably just need to get myself another chromebook for dev/test stuff ... ;)

Have you tried this in your manifest?
https://developer.chrome.com/apps/experimental

**Comment by cwegener** [comment]
So, I've just enabled chrome://flags/#enable-experimental-web-platform-features on M36 running on my Chromebook.
And I've loaded jstorrent-fresh
But how do I confirm if the WebCrypto API is used or if the hashes are still 'manually' generated in JavaScript?
Can the workerthread.js output some debug/verbose info into the Javascript console?

**Comment by cwegener** [comment]
Though I have to say that my HP 11 definitely feels much snappier with a torrent running 'in the background' now that I've installed jstorrent-fresh and enabled exp. web platform ... I 'think' that according to task manager, JS torrent might actually be more CPU efficient now ... And other Chrome tasks still have plenty of spare CPU cycles that they can access ...

**Comment by kzahel** [comment]
Saw that this went stable in chrome 37 so it's working now!
