### ISSUE TITLE
Will not even start to download.

### ISSUE THREAD

**Issue by charlievdp** [kzahel/jstorrent-legacy-app#50]
When I add a .torrent file to the program, it does nothing for 30 seconds before a notification pops up saying 
"No peers were received from any trackers. Unable to download. Try a more popular torrent or a different torrent site. Or you can
a) Add public trackers and reattempt
b) Do nothing"

I have an HP 11 Chromebook that I bought yesterday and am trying to set it up. There are not really any trackers or anything like that. What are my options? Thanks.

**Comment by kzahel** [comment]
Did anything happen once you clicked on add public trackers?
Are you familiar with what a tracker is? It's the thing that tells you the other peers in the swarm to download from. If your torrent file doesn't have any trackers, then it might be a "trackerless" (DHT) torrent which JSTorrent doesn't really have support for, but most of the time there will be peers on a public tracker anyway.

Does this make sense to you?

**Comment by ghost** [comment]
I'm getting this error on all torrents.

**Comment by kzahel** [comment]
Are they private torrents? Most private trackers do not support JSTorrent. There is a "spoofing" option but could run afoul of your tracker rules.

**Comment by ghost** [comment]
All the torrents I've tried it on have had 50+ seeders. But I guess it's
possible.

Maybe you could send me a dummy torrent to test it out on.

**Comment by kzahel** [comment]
I updated the list of public trackers in the latest release so it should be working now!
