### ISSUE TITLE
can't find trackers 

### ISSUE THREAD

**Issue by robertt202** [kzahel/jstorrent-legacy-app#51]
it worked fine once I figured out I needed to select a download location.

for the last couple of weeks I have been getting a "no trackers found" error message.

I'm using eztv.it and when I use the same site for my windows 7 desktop everything is fine.

any suggestions?

**Comment by kzahel** [comment]
looks like eztv.it is using base32 encoding, which i am parsing incorrectly... let me look to see why i'm not decoding that

**Comment by robertt202** [comment]
thanks!

weird thing is, it worked just fine when I first got it.
appreciate the help

-----Original Message-----

**Comment by kzahel** [comment]
fixed https://github.com/kzahel/jstorrent/commit/2d3afd57bb626d5305bbe786144776b893c8ccd0
are you running from source?
i probably wont do a full release yet for the auto updated app... unless you demand it :-)

**Comment by robertt202** [comment]
no I got this from the play store - 

no need to update it on my account - I'll wait for your next release.

most of my downloads are from the desktop anyway

just glad to know I'm not losing my mind :)

-----Original Message-----
