### ISSUE TITLE
chrome-extension://invalid/ when trying to "Play" video

### ISSUE THREAD

**Issue by jtimtaylor** [kzahel/jstorrent-legacy-app#53]
I recently purchased your app for the ability to play streaming torrents on my Samsung Chromebook, and ultimately cast them to the Chromecast.  For my first test, I initiated a torrent and waited a few minutes for it to download a decent chunk of the movie.  Then I navigated to the Files tab and clicked the "Play" link.  The link launched a tab in ChromeOS with the url "chrome-extension://invalid/".  As you might expect, no movie was playing.

Thoughts?

**Comment by kzahel** [comment]
This broke when I switched to the new chrome.sockets API. I'm going to be fixing it soon... stay tuned.

For now you should be able to play the files through chromecast video player once the file is 100% complete.

Thanks for letting me know!

**Comment by kzahel** [comment]
Working on this today ...
https://github.com/kzahel/web-server-chrome/commit/12c63f8b96fd9f44e215fd214cc3710ba40251cb
Still needs some more work

**Comment by IamMille** [comment]
I'm on Chromebook too. I can't seam to find the "play" link under the Files tab. 

Are Chromebooks not currently supported or is there perhaps an other problem?

**Comment by kzahel** [comment]
I added the "Play" option in the latest release. Works on chromebooks.
