### ISSUE TITLE
Cannot load torrent - Disk missing after ChromeOS updates.

### ISSUE THREAD

**Issue by wellrest** [kzahel/jstorrent-legacy-app#62]
Hello,

I love using a native Torrent client for quickie downloads, but it seems to generate the same error every time the ChomeOS updates, "Cannot load torrent - Disk missing".  This is the second time it's happened; I believe that it's happened shortly after ChromeOS updates (I don't run JSTorrent very often, so I can't say for sure).

If it matters, I do run Linux on the side, via Crouton.

Thank you,

~Adam

**Comment by kzahel** [comment]
Yup! You're not the only one seeing this. I also find it to be VERY annoying! I filed an issue on crbug, but it hasn't had any attention. If you would "star" it there it would help get more attention.

Edit: here is the link: https://code.google.com/p/chromium/issues/detail?id=410773

**Comment by sabu140** [comment]
So what is the solution?

**Comment by kzahel** [comment]
Solution is:
- click "remove directory" in the popup that appears in the notifications
- go to the app options, click "choose download directory" and pick the directory
- now remove and re-add any torrents to use the new directory

**Comment by kzahel** [comment]
Seems like this is no longer a problem (hopefully). I just had my machine auto-updated and didn't have to re-select the directory

**Comment by wellrest** [comment]
I'm in the same boat, the update wasn't an issue. It did, however, break my
linux installation.  But that is for another forum!

**Comment by kzahel** [comment]
Mine was acting up too. But I updated my crouton chroot (ubuntu precise) and it's working better than ever!

**Comment by wellrest** [comment]
Very nice... I seem to recall was a few simple flags and -update CHROOTNAME?
