### ISSUE TITLE
Can't find more than one peer

### ISSUE THREAD

**Issue by oletche** [kzahel/jstorrent-legacy-app#65]
Since last Chromebook update (37.0.2062.120) I can't download any torrent using JSTorrent version  2.3.0 (paid version). It only finds one peer but download doesn't start or list of peers and swarms isn't updated. I've tryied different torrents sources such as The Pirate Bay but they have all failed.

**Comment by kzahel** [comment]
Did you re-select the download directory in the options? Every time chrome updates you have to do this because of a bug with google's chrome.fileSystem.retainEntry 

Try that, and let me know if it helps. Otherwise I'll have to think more about what the problem might be.

**Comment by oletche** [comment]
Been that, done that. But doesn't work.
I've already tryed to re-install app, tryed free version and selecting spoofing option. None of them work. Thought maybe it was my ISP, but I tested on a notebook running Windows and uTorrent and it works fine.

![01](https://cloud.githubusercontent.com/assets/8887817/4380875/66b2c9a8-436e-11e4-9f82-b46753909a74.png)
![02](https://cloud.githubusercontent.com/assets/8887817/4380876/66cc7a38-436e-11e4-8991-ae3795a1675a.png)

**Comment by kzahel** [comment]
Well, it looks like you just found a very unpopular torrent... ?

However if the same torrent link works in another client, it's possible there's an error with how I'm decoding the magnet link (I made an error in decoding base32 before...). You can share the magnet link or email the .torrent file to graehlarts@gmail.com and I can see if it reproduces on my side...

However just because something works in uTorrent doesn't mean it'll work in JSTorrent. JSTorrent doesn't have any protocol encryption support, which circumvents basic ISP filtering...

**Comment by oletche** [comment]
Well, don't know what to say, kzahel.
I tryed to download the same torrent with Bitford - on my Chromebook - and it worked fine.
With JSTorrent, unfortunately, I can't establish any connection. It bothers me 'cause I bought JSTorrent thinking it would be my best solution. Now I'm using a free app to do the same thing I used to do few days ago. But, I'm sending you the .torrent file so you can analyze it better. Thanks!

**Comment by kzahel** [comment]
@oletche appreciate it. Going to look into what the problem is

**Comment by kzahel** [comment]
Did I ever get back to you on this? Did you have any luck with the latest update?

**Comment by oletche** [comment]
Hey, Graehl.

Yes! Since the last update all my torrents are working fine.
Thanks for all your help and for make even better this awesome app.

All the very best.

_César Paladini_
about.me/oletche
Blumenau - SC

2014-10-22 0:26 GMT-02:00 Kyle Graehl notifications@github.com:
