### ISSUE TITLE
Unable to download after powerwash

### ISSUE THREAD

**Issue by JonCStewart** [kzahel/jstorrent-legacy-app#67]
Recently backed up what little there was on my HP Chromebook 14"; power washed & logged into to a new Chomebook. As of right now I am completely unable to download JStorrent- In the Chrome webstore is says "Not Compatible" although the "Helper extension" is still installed. Here is a photo for reference, any help is greatly appreciated!
![screenshot 2014-10-10 at 8 31 32 am](https://cloud.githubusercontent.com/assets/9137453/4594791/b4b35a6a-5092-11e4-988c-bee150a9f2c3.png)

**Comment by kzahel** [comment]
What version of chrome? Perhaps you reverted to a very old version somehow
when you power washed. It needs to be at least 33. Leave your computer on
and plugged into power and it should update itself. Let me know if this
isn't the problem

**Comment by JonCStewart** [comment]
You called it! I was expecting it to update automatically but I'm guessing I have that feature switched off. All I had to do was click "restart to update" in the settings tray & I was back in business! Thanks so much!
