### ISSUE TITLE
Paypall

### ISSUE THREAD

**Issue by mishapapa** [kzahel/jstorrent-legacy-app#70]
Can i pay jstorrent with paypall on google store?

**Comment by kzahel** [comment]
No, you can only pay with google wallet. If it's not supported in your country, you could try installing ZenMate for chrome and changing your country.

Or, you can use the free trial version https://chrome.google.com/webstore/detail/jstorrent-lite/abmohcnlldaiaodkpacnldcdnjjgldfh ...
or run from source...
