### ISSUE TITLE
can i use jsTorrent to play torrent video steam ?

### ISSUE THREAD

**Issue by kenchan97** [kzahel/jstorrent-legacy-app#71]
i want to play the video torrent with out download whole files .
play the mp4 video without 100% download , 
possible to do this ?

**Comment by kzahel** [comment]
Yes, however when I migrated to the new chrome.sockets API I broke this functionality and I disabled it for now. I'll be fixing it up and adding it back in. You can edit the options.js file and re-enable it if you run from source code to see how it works (not very well right now)

**Comment by kenchan97** [comment]
sorry , can you tell me more about how to enable video steam function?
i duno where should i edit.

**Comment by kzahel** [comment]
I'll spend some time soon trying to get it working again. I think now even if you edited in js/options.js it would still not function well.

**Comment by kzahel** [comment]
I now shipped this in the latest release. give it a try!
