### ISSUE TITLE
How to move purchase to different account

### ISSUE THREAD

**Issue by fredmanson** [kzahel/jstorrent-legacy-app#73]
Hi§§ I have bough JStorrent on my Chromebook with my last Google account. Unfortunately, due to some "sniffing" in my Google account, I deleted it. I wanted to add JStorrent in the new Google account but I can't: not the same Google account name AND security. How could I have JStorrent to work on my same Chromebook but under a different Google account name without to pay it a second time?? Thanks for watching!!

**Comment by kzahel** [comment]
Hey, I think the easiest thing to do is you send me your order # either here or by emailing to graehlarts@gmail.com and I can refund it; then you can re-purchase. Sound good?
