### ISSUE TITLE
jstorrent invalid file on all files??

### ISSUE THREAD

**Issue by jessicarebekah** [kzahel/jstorrent-legacy-app#76]
I've recently purchased a chromebook so have no choice but to use jstorrent 

However every single file I try to use comes up as 'invalid torrent' it's getting pretty annoying.

Am I doing something wrong should I be using a specific torrent site?

**Comment by kzahel** [comment]
sorry about the trouble. can you send a torrent file that gives this error
to graehlarts@gmail.com so I can fix the problem?
