### ISSUE TITLE
error with torrent

### ISSUE THREAD

**Issue by traveller1951** [kzahel/jstorrent-legacy-app#77]
torrent starts downloading but when I stop and then restart error with torrent cannot load torrent not found error appears. m I doing something wrong

**Comment by kzahel** [comment]
Hmm, did you select a download directory in the options? Try that, removing the torrent, and adding it again.

**Comment by traveller1951** [comment]
have a place for the downloads to go and readding the download works fine. But the problem is I have a download allowance so lose what I've downloaded. Thanks for getting back to me.

**Comment by kzahel** [comment]
Sorry, I'm having a difficult time understanding. So you are able to download OK, but when you stop mid-download it is unable to start the download again?

There could be a problem with the torrent file; if you like you could send it to me at graehlarts@gmail.com and I could make sure it's not a problem with the torrent
