### ISSUE TITLE
State:error

### ISSUE THREAD

**Issue by gamerguy1000** [kzahel/jstorrent-legacy-app#78]
Hi, I recently just got JSTorrent and I tried downloading Big Bang Theory, which does have a lot of seeds. Yes, I have located a download folder and yes there were trackers. The state was still error when it was immediately placed in JSTorrent. How do I fix this? Thank you.

**Comment by kzahel** [comment]
Were you using a magnet link? Can you maybe go to chrome://inspect and go to apps and click on inspect JSTorrent and then go to the console and see if anything is printed there?

**Comment by gamerguy1000** [comment]
Failed to load resource: net::ERR_FILE_NOT_FOUND chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/js/web-server-chrome/common.js
Failed to load resource: net::ERR_FILE_NOT_FOUND chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/js/web-server-chrome/mime.js
Failed to load resource: net::ERR_FILE_NOT_FOUND chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/js/web-server-chrome/buffer.js
Failed to load resource: net::ERR_FILE_NOT_FOUND chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/js/web-server-chrome/request.js
Failed to load resource: net::ERR_FILE_NOT_FOUND chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/js/web-server-chrome/stream.js
Failed to load resource: net::ERR_FILE_NOT_FOUND chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/js/web-server-chrome/connection.js
Failed to load resource: net::ERR_FILE_NOT_FOUND chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/js/web-server-chrome/webapp.js
Failed to load resource: net::ERR_FILE_NOT_FOUND chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/js/web-server-chrome/handlers.js
Failed to load resource: net::ERR_FILE_NOT_FOUND chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/js/web-server-chrome/httplib.js
window.onerror triggered Uncaught ReferenceError: BaseHandler is not defined chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/js/webhandlers.js 27 common.js:360
Uncaught ReferenceError: BaseHandler is not defined webhandlers.js:27
received sync app attributes Object app.js:61
app:initialize_client app.js:281
collection.fetch undefined collection.js:249
restoring disk with id 6C9D613BD3F41ABEE01B695CCDD9FFBA:SD Card disk.js:64
restored 6C9D613BD3F41ABEE01B695CCDD9FFBA:SD Card disk.js:66
successfully restored disk entry 6C9D613BD3F41ABEE01B695CCDD9FFBA:SD Card disk.js:90
onDiskReady 1 1 client.js:74
collection.fetch undefined collection.js:249
oncontextmenu Torrent app.js:183
Object torrent.js:660
report job err NotFoundError diskio.js:640

That is what is printed in the console.

**Comment by kzahel** [comment]
oh. you're running from source? you'll need to get another project of mine
off github called web server chrome

**Comment by gamerguy1000** [comment]
Ok, I downloaded it and it still gives me the error. What do I do now?

**Comment by kzahel** [comment]
try jstorrent lite. the free version.
https://chrome.google.com/webstore/detail/jstorrent-lite/abmohcnlldaiaodkpacnldcdnjjgldfh

**Comment by gamerguy1000** [comment]
State is now started. ETA: Infinite. There are multiple trackers but the lasterror says timeout. A message popped up saying to add more trackers and such.

**Comment by kzahel** [comment]
Any improvement after adding public trackers?

**Comment by gamerguy1000** [comment]
No

**Comment by kzahel** [comment]
I made a fix for trackers the other day. I'll push out an update soon that should address your issue.
