### ISSUE TITLE
Please make a full version available for the following market "en-GB: sl-SI, sl, en-GB, en"

### ISSUE THREAD

**Issue by gabbax** [kzahel/jstorrent-legacy-app#79]
copied from trial version:
If for some reason, the full version is not available in your market or country, please let me know on the JSTorrent community page on Google+, and I will remove the download restriction for these markets. Please include this information: Your market: "en-GB: sl-SI, sl, en-GB, en"

otherwise, it rocks. 5 stars

**Comment by kzahel** [comment]
Thanks for letting me know.
Can you also try one thing and see if it works? Install ZenMate for Chrome, it's a free VPN software that works for Chrome. You should be able to try in another market and see a price.

Is SL slovenia? I can make it unlimited there in the next release.

**Comment by gabbax** [comment]
Please do, yes, Slovenia. Hurry please, only 4 DL's left :)
Will try ZenMate.
BTW I'm on Chromebook computer, not just browser. There are not a lot of other options left for CB users :)

**Comment by kzahel** [comment]
Also if you run out of downloads you can email me at support@jstorrent.com and I can give you instructions for how to unlock more downloads.
