### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by zakhar92** [kzahel/jstorrent-legacy-app#8]
when i copy the address bar into the jst nothing happens or opens i had this app before the recent update it worked, any help????, like site suggestions (i use pirate bay and kat) and how to copy url???

**Comment by kzahel** [comment]
https://chrome.google.com/webstore/detail/jstorrent-helper-extensio/bnceafpojmnimbnhamaeedgomdcgnbjk Try installing the helper extension. Then you should have a special item in your right click menu on any magnet or torrent link on those websites (Add to JSTorrent)
