### ISSUE TITLE
Can't buy in the Chrome Web Store

### ISSUE THREAD

**Issue by frontalot** [kzahel/jstorrent-legacy-app#82]
Download / purchase button says "price not available."

**Comment by kzahel** [comment]
Two things to try. Click on Settings icon near top right of the Chrome Web Store. Choose a different country.

If that doesn't work, you can install "ZenMate" for Chrome, which can be found in the web store. It lets you change your country using their free VPN.

Lastly, you might try using the free trial of JSTorrent https://chrome.google.com/webstore/detail/jstorrent-lite/abmohcnlldaiaodkpacnldcdnjjgldfh , or installing from source using the instructions in the README here on github
