### ISSUE TITLE
Buttons not working, torrent files not coming up

### ISSUE THREAD

**Issue by keving139** [kzahel/jstorrent-legacy-app#84]
Starting today (1/14/15) worked fine yesterday the app is does not open when selecting a torrent file, and when open from the menu bar, no buttons are working.  Also Quit button does not work.   

here is the error log:

window.onerror triggered Uncaught TypeError: Cannot read property 'web_server_enable' of null chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/js/options.js 142
options.js:142 Uncaught TypeError: Cannot read property 'web_server_enable' of null
index.html:1 Can't open same-window link to "chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/gui/index.html?"; try target="_blank".

Chrome OS 39.0.2171.96

Thanks

**Comment by kzahel** [comment]
Sorry I released an update to deal with an API deprecation without properly testing. :-(
I released a fix that will auto update itself.

**Comment by kzahel** [comment]
Also you can quit by pressing Ctrl-W. Sorry about the trouble!

**Comment by keving139** [comment]
thanks for fixing much appreciated.
