### ISSUE TITLE
All Trackers Timing Out

### ISSUE THREAD

**Issue by joeyhens** [kzahel/jstorrent-legacy-app#85]
Every time I add a torrent, every tracker times out, even torrents that I know have peers available (because I tried adding the same torrents to BitTorrent on my desktop computer). I tried uninstalling and reinstalling the software. Any ideas?

**Comment by amvarela** [comment]
It's been like that for me since 3 days ago.

**Comment by kzahel** [comment]
Thanks. I figured out what the problem was. I pushed a fix and you should get an auto-update to version 2.3.10. There was a problem with an uninitialized variable :-( But all should be good now!
