### ISSUE TITLE
Download speed drops/stops at 99%

### ISSUE THREAD

**Issue by mjmoores** [kzahel/jstorrent-legacy-app#86]
Hi, download the app about a week ago, i've been unable to download a torrent as of yet (smallest i've tried is 700mb). The reason being is the download speed drops to single bytes or just stops completely at around 99%

This happens on numerous torrents, not just the ones shown below. Doesn't matter if I minimise the app, restart the app or stop and start the torrent. Any thoughts?

**Comment by kzahel** [comment]
Did you try closing / restarting the app? It can start to slow down and hang after about 2-3GB downloaded. If that doesn't help try a full reboot. Please let me know if this helps any

**Comment by kzahel** [comment]
Also take a look in the Peers tab and make sure there are some peers with 100%

**Comment by kzahel** [comment]
Also it can happen with very new torrents, that there are not too many peers that have the full 100% of the file. And those who do, are not seeding to you. It can help to let the program run for a while longer...

**Comment by kzahel** [comment]
I identified and fixed a lot of bugs having to do with downloads freezing and you should get the fix in the latest update.

**Comment by Chaitanya123321** [comment]
From phone app settings force stop the app and open utorrent again...
