### ISSUE TITLE
Search bar with Material Design overhaul

### ISSUE THREAD

**Issue by ghost** [kzahel/jstorrent-legacy-app#87]
Curious about what everyone thinks of adding a search bar through material design overhaul and then link it directly to a customizable torrent directory.

**Comment by kzahel** [comment]
What would the search bar do? Filter the current list of torrents?

**Comment by ghost** [comment]
Just have the ability to link any search field (input box)you find on the web and then redirect the user to the website? Or the user could build the url and the user could insert different exception for the website. But the filtering idea would be a nice addition also. Maybe with a command based approach. so type filter 'tab' and then also for filter search same with the search option.
