### ISSUE TITLE
multiple errors

### ISSUE THREAD

**Issue by reaganpape** [kzahel/jstorrent-legacy-app#88]
Yesterday I have started to get multiple errors. Torrents will start to download and then stop after a few minutes. Some of the errors have been "error persisting piece entrygetter" and "no modification allowed." I am on a chromebox.

**Comment by kzahel** [comment]
Try changing your download directory, removing the torrents, and adding them again.

Double check that you have write permission to the directory (open Files app and try to create a directory)

**Comment by reaganpape** [comment]
Thank you for the quick response, changing the directory appears to have solved the problem. Much appreciated. 

```
 On Monday, February 2, 2015 12:27 PM, Kyle Graehl <notifications@github.com> wrote:
```

 Try changing your download directory, removing the torrents, and adding them again.Double check that you have write permission to the directory (open Files app and try to create a directory)—
