### ISSUE TITLE
DOMException: Only secure origins are allowed.

### ISSUE THREAD

**Issue by beaufortfrancois** [kzahel/jstorrent-legacy-app#89]
I cannot download torrents anymore at all due to this error below:

``` javascript
DOMException: Only secure origins are allowed. http://goo.gl/lq4gCo
```

![screenshot 2015-02-18 at 8 21 06 am](https://cloud.githubusercontent.com/assets/634478/6243681/3437dea8-b747-11e4-8f79-f017e225c91d.png)

```
Google Chrome   42.0.2302.4 (Official Build) dev (64-bit)
Platform    6783.1.0 (Official Build) dev-channel link
```

**Comment by beaufortfrancois** [comment]
After a quick check, it looks like it's related to `crypto`.
Even though http://crbug.com/412681 says it should be OK, I'm still seeing this error and I wonder if http://crbug.com/439323 could be related or not.

I will try to isolate this use case (worker loading crypto in a chrome app) now.

**Comment by beaufortfrancois** [comment]
I was able to reproduce the issue and I've filed a bug at http://crbug.com/459515.
Stay tuned!

**Comment by kzahel** [comment]
Hmm interesting. I haven't been looking on dev channel so didn't catch
this. I think I should probably fallback to not using crypto.subtle if I
get that DOMException, though. Thanks for noticing this!

**Comment by kzahel** [comment]
I thought about just putting in a quick (! navigator.userAgent.match("Chrome/42") before using crypto.subtle but was wondering if you know a way to check which channel (access to chrome://version platform or something) in javascript. Couldn't find anything in chrome.*

Also I couldn't tell how many users are in which channel, that information is not in google analytics :-(

**Comment by beaufortfrancois** [comment]
As you can see at https://codereview.chromium.org/941313002, they've fixed the issue and I can download torrents successfully in Chrome Canary with this patch in JSTorrent.

Regarding your issue, `navigator.userAgent.match` is actually your best best of checking chrome version.

**Comment by beaufortfrancois** [comment]
Are you aware of https://github.com/GoogleChrome/chrome-platform-analytics/wiki?
