### ISSUE TITLE
Download extremely slow. 

### ISSUE THREAD

**Issue by llaera** [kzahel/jstorrent-legacy-app#90]
Hey folks,
I use the Acer Chromebook C720P, so with an Intel architecture. So I have a Internet connection of 50mbit/s download and 50mbit/s upload. On JSTorrent I get 550B/s of download and on my mac, same configuration, same internet connection and same trackers and peers, I get 2mb/s.
Yes I use the newest version.
Does anyone has a solution?

Have a nice day,
Loris Laera

**Comment by kzahel** [comment]
less than 1KB sounds like no peers are seeding to you. How many peers are you connected to? Can you send a screenshot of your Peers tab?

**Comment by llaera** [comment]
Here you got 2 screenshots:http://imgur.com/1QYKkpp,qIJBm0Q#0http://imgur.com/1QYKkpp,qIJBm0Q#1

Date: Mon, 23 Feb 2015 12:05:25 -0800

**Comment by llaera** [comment]
For everyone here are 2 screenshots:
http://imgur.com/qIJBm0Q
http://imgur.com/1QYKkpp

**Comment by kzahel** [comment]
Hmm so only 50 people in the swarm... which is not very many. Looks like
other people have their upload limited and they haven't "unchoked" you

How many people in the swarm using utorrent?

**Comment by llaera** [comment]
Pretty strange because on my mac I get 2mb/s ?!

**Comment by kzahel** [comment]
Well maybe not too strange. on the mac utorrent could know about more peers
because it's using DHT. If you could check how big the swarm size is there,
that would be good info to have

**Comment by llaera** [comment]
On transmission I get 50 as Swarm

**Comment by kzahel** [comment]
Fixed a ton of bugs with downloads pasing/freezing. Let me know if you still have problems.
