### ISSUE TITLE
Missing Maximize/Minimize Buttons

### ISSUE THREAD

**Issue by noelleleigh** [kzahel/jstorrent-legacy-app#91]
Love the app, but does the custom window bar it uses mean you can't include native window management controls?

**Comment by kzahel** [comment]
Yes that was a case of bad planning. Ideally I would have only added a button without ruining the normal minimize buttons. I'm planning on doing a UI overhaul and by that time there may be more chrome app api changes that make such a thing easier.

For now you can click on the app in the task tray to minimize/unminimize. Works just the same as if you used a minimize button...

**Comment by noelleleigh** [comment]
Yeah, clicking on the shelf icon is what I do now. Looking forward to the UI overhaul! It could definitely use some polish. Polymer with Material Design perhaps?

**Comment by gonzalezb** [comment]
https://github.com/gonzalezb/jstorrent

i requested a pull request back in February still sitting there and no response just unzip it and load the extension manually. In other words took me 2 minutes to make the changes and its still fully functional.

**Comment by kzahel** [comment]
Hi sorry about not getting back to you earlier. I went ahead and also removed the minimize/compact buttons, as they did not work very well.

I plan to support background mode operation in a future update, which will be a little like the app only lives in the taskbar. Thanks for all the help and feedback.
