### ISSUE TITLE
Download freezing

### ISSUE THREAD

**Issue by gonzalezb** [kzahel/jstorrent-legacy-app#93]
Does not always happen but it does allot but sometimes the download will stop half way through the download or a quarter of the way and just sit there to fix it you have to stop it then let it sit for 10 to 15 minutes then restart it and sometimes it will happen twice with the same torrent but that rarely happens mostly only happens once with the a torrent.

**Comment by kzahel** [comment]
I fixed a bunch of bugs that were causing downloads to stop. Now should handle many many GB without stopping/freezing
