### ISSUE TITLE
error messages every time I try and add a file

### ISSUE THREAD

**Issue by xx-lulu-xx** [kzahel/jstorrent-legacy-app#97]
I am new to chromebook and just downloaded js torrent.

Everytime I try and add a torrent file from my downloads I get the following error messages:

Error with torrent:Disk missing. Choose a download directory in the options, or remove it and add it again.

("error":"invalid torrent file"."info":{}}

Is there a problem with the files I am downloading? Maybe I am doing something wrong.

**Comment by kzahel** [comment]
Click on options in the app and then click on choose download directory.
Pick a place to download the torrents. Then remove the torrents from the
app and try again

**Comment by xx-lulu-xx** [comment]
It's working now, Thanks so much for your help.
