### ISSUE TITLE
Torrents won't download

### ISSUE THREAD

**Issue by eloisw** [kzahel/jstorrent-legacy-app#98]
% Complete shows Not a Number, Upload Speed and uploaded bytes show as positive values at the beginning, then eventually die off.  Peers show, state connected, % Complete 0, Bytes sent 131, received 0, etc. for all peers.  Last sent: UTORRENT_MSG, Last received, blank, timeouts 0, amChoked true, peerChoked, true

**Comment by kzahel** [comment]
Hmm not receiving any data from any peers... that sounds very strange. How many peers total? This could be your ISP filtering traffic. Can you try on another connection?
