### ISSUE TITLE
Downloading from private trackers not working

### ISSUE THREAD

**Issue by BraveSirRobbo** [kzahel/jstorrent-legacy-app#99]
I'm attempting to download from multiple private trackers (broadcasthe.net, what.cd, torrentleech.org), but jstorrent isn't finding peers.  I'm using spoofing, but it's not working - any ideas ?  Could it be that those sites know how to get around it ?  Or simply that you've broken it ?  Let me know if you want me to give more info

**Comment by kzahel** [comment]
Thanks for the feedback. I can troubleshoot if you want to send me an invite to what.cd - send it to support@jstorrent.com

The upcoming Chrome version 44 will actually allow seeding (the first version of Chrome which allows listening on ports), so I'm going to put in some work to make sure it can work better with private trackers.

**Comment by BraveSirRobbo** [comment]
Invite sent, good luck :)

**Comment by BraveSirRobbo** [comment]
Did you get anywhere with this ?
